//! Rust port of the MINIX/NetBSD `msgc` utility.
//!
//! Usage:
//!   msgc inputfile
//!
//! Message compiler - processes message source files.

use std::collections::HashMap;
use std::fs;
use std::io::{BufRead, BufReader, Write};

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let argv = &args[1..];

    if argv.is_empty() {
        eprintln!("usage: msgc inputfile");
        std::process::exit(1);
    }

    let input = argv[0].clone();
    let file = match fs::File::open(&input) {
        Ok(f) => f,
        Err(e) => { eprintln!("msgc: {input}: {e}"); std::process::exit(1); }
    };

    let reader = BufReader::new(file);
    let mut outputs: HashMap<String, Vec<String>> = HashMap::new();
    let mut current_file = String::new();

    for line in reader.lines() {
        let line = match line { Ok(l) => l, Err(_) => break };
        let trimmed = line.trim();

        if trimmed.starts_with("file ") {
            current_file = trimmed.trim_start_matches("file ").trim().to_string();
            outputs.entry(current_file.clone()).or_default();
        } else if !trimmed.is_empty() && !trimmed.starts_with('#') {
            if !current_file.is_empty() {
                outputs.get_mut(&current_file).unwrap().push(trimmed.to_string());
            }
        }
    }

    for (fname, msgs) in &outputs {
        let out_name = format!("{}.c", fname);
        let mut out = fs::File::create(&out_name)
            .unwrap_or_else(|_| { eprintln!("msgc: cannot create {out_name}"); std::process::exit(1); });

        writeln!(out, "/* Generated by msgc */").ok();
        writeln!(out, "#include <msg.h>\n").ok();
        for msg in msgs {
            let parts: Vec<&str> = msg.splitn(2, ' ').collect();
            if parts.len() == 2 {
                writeln!(out, "msg(\"{}\", \"{}\");", parts[0], parts[1]).ok();
            } else {
                writeln!(out, "/* {} */", msg).ok();
            }
        }
    }
}
