//! Rust port of the NetBSD `mkcsmapper` utility.
//!
//! Usage:
//!   mkcsmapper [-o output] [input ...]
//!
//! Generates charset mapping tables for character set conversion.
//! Processes mapping definition files and outputs C header/source.

use std::collections::BTreeMap;
use std::fs;
use std::io::{BufRead, BufReader, Write};

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let mut argv = &args[1..];
    let mut output: Option<String> = None;

    while !argv.is_empty() && argv[0].starts_with('-') && argv[0] != "--" {
        let opt = argv[0].clone();
        if opt == "--" { argv = &argv[1..]; break; }
        match opt.as_str() {
            "-o" => {
                argv = &argv[1..];
                if argv.is_empty() { eprintln!("usage: mkcsmapper [-o output] [input]"); std::process::exit(1); }
                output = Some(argv[0].clone());
            }
            _ => { eprintln!("usage: mkcsmapper [-o output] [input]"); std::process::exit(1); }
        }
        argv = &argv[1..];
    }

    let inputs: Vec<&str> = if argv.is_empty() { vec!["-"] } else { argv.iter().map(|s| s.as_str()).collect() };
    let mut mappings: BTreeMap<u32, u32> = BTreeMap::new(); // from_cp -> to_unicode
    let mut charset_name = String::new();
    let mut direction = "both";

    for fname in &inputs {
        let reader: Box<dyn BufRead> = if *fname == "-" {
            Box::new(BufReader::new(std::io::stdin().lock()))
        } else {
            match fs::File::open(fname) {
                Ok(f) => Box::new(BufReader::new(f)),
                Err(e) => { eprintln!("mkcsmapper: {fname}: {e}"); std::process::exit(1); }
            }
        };

        for line in reader.lines() {
            let line = match line { Ok(l) => l, Err(_) => break };
            let trimmed = line.trim();

            if trimmed.is_empty() || trimmed.starts_with('#') { continue; }
            if trimmed.starts_with("name ") {
                charset_name = trimmed.trim_start_matches("name ").trim().to_string();
                continue;
            }
            if trimmed.starts_with("direction ") {
                direction = trimmed.trim_start_matches("direction ").trim();
                continue;
            }

            // Format: 0xHH 0xHH  (from to)
            let parts: Vec<&str> = trimmed.split_whitespace().collect();
            if parts.len() >= 2 {
                let from = parse_hex(parts[0]);
                let to = parse_hex(parts[1]);
                if let (Some(f), Some(t)) = (from, to) {
                    mappings.insert(f, t);
                }
            }
        }
    }

    let out_name = output.unwrap_or_else(|| {
        if charset_name.is_empty() { "csmap.c".to_string() } else { format!("{}.c", charset_name) }
    });

    let mut out = fs::File::create(&out_name)
        .unwrap_or_else(|_| { eprintln!("mkcsmapper: cannot create {out_name}"); std::process::exit(1); });

    writeln!(out, "/* Generated by mkcsmapper */").ok();
    writeln!(out, "#include <csmap.h>\n").ok();
    writeln!(out, "static const struct csmap_entry {}[{}] = {{",
        if charset_name.is_empty() { "csmap" } else { &charset_name },
        mappings.len()).ok();
    for (from, to) in &mappings {
        writeln!(out, "    {{ 0x{:04x}, 0x{:04x} }},", from, to).ok();
    }
    writeln!(out, "}};").ok();
    writeln!(out, "\nconst int {}_nentries = {};",
        if charset_name.is_empty() { "csmap" } else { &charset_name },
        mappings.len()).ok();
}

fn parse_hex(s: &str) -> Option<u32> {
    let s = s.trim();
    if s.starts_with("0x") || s.starts_with("0X") {
        u32::from_str_radix(&s[2..], 16).ok()
    } else if s.ends_with('h') || s.ends_with('H') {
        u32::from_str_radix(&s[..s.len()-1], 16).ok()
    } else if s.chars().all(|c| c.is_ascii_hexdigit()) {
        u32::from_str_radix(s, 16).ok()
    } else {
        None
    }
}
