# Makefile - BSD Make build for Rust basename utility
#
# Builds the basename utility from Rust source using cargo.
# Requires: cargo (Rust toolchain)

.include "../Makefile.inc"

PROG=	basename

.include <bsd.prog.mk>
