//! Rust port of the MINIX/NetBSD `menuc` utility.
//!
//! Usage:
//!   menuc [-o output] inputfile
//!
//! Compiles menu description files for sysinstall-like programs.

use std::fs;
use std::io::{BufRead, BufReader, Write};

struct MenuItem {
    name: String,
    label: String,
    action: String,
    selected: bool,
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let mut argv = &args[1..];
    let mut output: Option<String> = None;

    while !argv.is_empty() && argv[0].starts_with('-') && argv[0] != "--" {
        let opt = argv[0].clone();
        if opt == "--" { argv = &argv[1..]; break; }
        match opt.as_str() {
            "-o" => {
                argv = &argv[1..];
                if argv.is_empty() { eprintln!("usage: menuc [-o output] inputfile"); std::process::exit(1); }
                output = Some(argv[0].clone());
            }
            _ => { eprintln!("usage: menuc [-o output] inputfile"); std::process::exit(1); }
        }
        argv = &argv[1..];
    }

    if argv.is_empty() {
        eprintln!("usage: menuc [-o output] inputfile");
        std::process::exit(1);
    }

    let input = argv[0].clone();
    let file = match fs::File::open(&input) {
        Ok(f) => f,
        Err(e) => { eprintln!("menuc: {input}: {e}"); std::process::exit(1); }
    };

    let reader = BufReader::new(file);
    let mut items: Vec<MenuItem> = Vec::new();
    let mut menu_name = "menu".to_string();

    for line in reader.lines() {
        let line = match line { Ok(l) => l, Err(_) => break };
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') { continue; }

        // Format: name|label|action|selected
        let parts: Vec<&str> = trimmed.split('|').collect();
        if parts.len() >= 2 {
            items.push(MenuItem {
                name: parts[0].to_string(),
                label: parts[1].to_string(),
                action: parts.get(2).unwrap_or(&"").to_string(),
                selected: parts.get(3).unwrap_or(&"0").trim() == "1",
            });
        } else if trimmed.starts_with("menu ") {
            menu_name = trimmed.trim_start_matches("menu ").trim().to_string();
        }
    }

    let out_name = output.unwrap_or_else(|| format!("{}.c", input));
    let mut out = fs::File::create(&out_name)
        .unwrap_or_else(|_| { eprintln!("menuc: cannot create {out_name}"); std::process::exit(1); });

    writeln!(out, "/* Generated by menuc from {} */", input).ok();
    writeln!(out, "#include <menu.h>\n").ok();
    writeln!(out, "struct menu_entry {}[] = {{", menu_name).ok();
    for item in &items {
        writeln!(out, "    {{ \"{}\", \"{}\", \"{}\", {} }},",
            item.name, item.label, item.action, if item.selected { 1 } else { 0 }).ok();
    }
    writeln!(out, "    {{ NULL, NULL, NULL, 0 }}").ok();
    writeln!(out, "}};").ok();
}
