# Makefile for minix-compositor (BSD Make / MINIX build)
#
# This allows `make -C rust/minix-compositor` to compile the crate.
# The actual build is delegated to cargo.

.include <bsd.own.mk>

PROG=	minix-compositor

.include <minix.cargo.mk>
