.include <bsd.own.mk>

.if ${MACHINE_ARCH} == "earm"
SUBDIR+=	eepromread
.endif # ${MACHINE_ARCH} == "earm"

SUBDIR+=	netstat
SUBDIR+=	pcapng
SUBDIR+=	rpcapd
SUBDIR+=	diff
SUBDIR+=	grep
SUBDIR+=	mined
SUBDIR+=	ministat
SUBDIR+=	mtop
SUBDIR+=	toproto
SUBDIR+=	trace

.include <bsd.subdir.mk>
