# Makefile - BSD Make subdir integration for Rust components
#
# This allows make (BSD Make) to recursively build Rust utilities.
#
# Usage:
#   cd ${NETBSDSRCDIR}/rust && make
#
# Or from the root build:
#   make -C rust

.include <bsd.own.mk>

SUBDIR+=	audio-buf
SUBDIR+=	basename
SUBDIR+=	cat
SUBDIR+=	chmod
SUBDIR+=	cksum
SUBDIR+=	cmp
SUBDIR+=	comm
SUBDIR+=	cp
SUBDIR+=	cut
SUBDIR+=	date
SUBDIR+=	dd
SUBDIR+=	df
SUBDIR+=	dirname
SUBDIR+=	domainname
SUBDIR+=	du
SUBDIR+=	echo
SUBDIR+=	env
SUBDIR+=	expand
SUBDIR+=	false
SUBDIR+=	fold
SUBDIR+=	grep
SUBDIR+=	head
SUBDIR+=	hostname
SUBDIR+=	id
SUBDIR+=	kill
SUBDIR+=	ln
SUBDIR+=	ls
SUBDIR+=	mkdir
SUBDIR+=	mv
SUBDIR+=	minix-alloc
SUBDIR+=	minix-driver
SUBDIR+=	minix-rs
SUBDIR+=	net-parse
SUBDIR+=	nl
SUBDIR+=	nohup
SUBDIR+=	paste
SUBDIR+=	pathchk
SUBDIR+=	printenv
SUBDIR+=	printf
SUBDIR+=	procfs-path
SUBDIR+=	pwd
SUBDIR+=	rm
SUBDIR+=	rmdir
SUBDIR+=	seq
SUBDIR+=	sleep
SUBDIR+=	sort
SUBDIR+=	split
SUBDIR+=	stat
SUBDIR+=	sync
SUBDIR+=	tail
SUBDIR+=	tee
SUBDIR+=	test
SUBDIR+=	time
SUBDIR+=	touch
SUBDIR+=	tr
SUBDIR+=	true
SUBDIR+=	tty
SUBDIR+=	uname
SUBDIR+=	unexpand
SUBDIR+=	uniq
SUBDIR+=	wc
SUBDIR+=	yes

.include <bsd.subdir.mk>
