#!/usr/bin/env bash
# ============================================================================
# qemu_test_net.sh — Phase 9.2: QEMU Network Smoke Test
#
# Boots a MINIX test image with network support and tests:
#   1. Network interface detection (e1000)
#   2. Loopback (lo0) ping
#   3. IPv6 loopback presence
#   4. ifconfig and route commands
#   5. Network stack initialization
#
# Usage:
#   ./scripts/qemu_test_net.sh                         # Build + boot + test
#   ./scripts/qemu_test_net.sh --image <path>           # Use pre-built image
#   ./scripts/qemu_test_net.sh --mode user              # QEMU user mode (default)
#   ./scripts/qemu_test_net.sh --mode tap               # Tap bridge (needs sudo)
#   ./scripts/qemu_test_net.sh --arch aarch64           # ARM64 test
#   ./scripts/qemu_test_net.sh --help                   # Show help
#
# Exit codes:
#   0 — All network tests passed
#   1 — Boot/network test failure
# ============================================================================

set -euo pipefail

# ─── Colors ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'

# ─── Paths ──────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-${SCRIPT_DIR}/build/qemu-test}"
RESULTS_DIR="${RESULTS_DIR:-$(pwd)/qemu-net-results}"
SERIAL_OUT="${RESULTS_DIR}/serial.txt"
SUMMARY="${RESULTS_DIR}/summary.txt"

# ─── Defaults ───────────────────────────────────────────────────────────
ARCH="${ARCH:-x86_64}"
IMAGE=""
TIMEOUT=120
NET_MODE="user"

# ─── Help ───────────────────────────────────────────────────────────────
usage() {
    cat <<EOF
Usage: $0 [options]

QEMU Network Smoke Test — boots MINIX and tests network stack.

Options:
  --image <path>    Use pre-built test image
  --arch <arch>     Architecture: x86_64 (default) or aarch64
  --mode <mode>     Network mode: user (default), tap, isolated
  --timeout <sec>   Boot timeout (default: 120)
  --help            Show this help

Exit codes:
  0 — All tests passed
  1 — Boot/network test failure

Examples:
  $0                          # Build + boot + test (user mode NAT)
  $0 --mode tap               # Tap bridge (needs sudo, bidirectional)
  $0 --image test.img         # Test with existing image
EOF
    exit 0
}

# ─── Parse arguments ────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --image)   IMAGE="$2"; shift 2 ;;
        --arch)    ARCH="$2"; shift 2 ;;
        --mode)    NET_MODE="$2"; shift 2 ;;
        --timeout) TIMEOUT="$2"; shift 2 ;;
        --help|-h) usage ;;
        *)         echo "Unknown: $1"; usage ;;
    esac
done

mkdir -p "$RESULTS_DIR"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}QEMU Network Smoke Test${NC}"
echo -e "${BLUE}========================================${NC}"
echo "Architecture: ${ARCH}"
echo "Network mode: ${NET_MODE}"
echo "Timeout:      ${TIMEOUT}s"
echo "Results:      ${RESULTS_DIR}"
echo ""

# ─── Check QEMU ─────────────────────────────────────────────────────────
QEMU=""
case "$ARCH" in
    x86_64)  QEMU="qemu-system-x86_64" ;;
    aarch64) QEMU="qemu-system-aarch64" ;;
    *)       echo -e "${RED}Unsupported arch${NC}"; exit 1 ;;
esac
command -v "$QEMU" &>/dev/null || { echo -e "${RED}${QEMU} not found${NC}"; exit 1; }

# ─── Locate or build image ──────────────────────────────────────────────
if [ -n "$IMAGE" ] && [ -f "$IMAGE" ]; then
    echo -e "${GREEN}Using image: ${IMAGE}${NC}"
else
    RC_LOCAL="${RESULTS_DIR}/rc_local.sh"
    cat >"$RC_LOCAL" <<'NET_RC'
#!/bin/sh
# Network smoke test rc.local — generated by qemu_test_net.sh

echo "NET:START"
START_TIME=$(date +%s 2>/dev/null || echo 0)

# Mount /proc
mount -t procfs none /proc 2>/dev/null || true

# Test 1: Network interface detection (lo0)
echo "NET:TEST=loopback"
if ifconfig lo0 2>/dev/null || ifconfig lo 2>/dev/null; then
    echo "NET:PASS:loopback_interface"
else
    # Try /sbin/ifconfig
    /sbin/ifconfig lo0 2>/dev/null && echo "NET:PASS:loopback_interface" || \
        echo "NET:FAIL:loopback_interface — lo0 not found"
fi

# Test 2: ifconfig listing
echo "NET:TEST=ifconfig"
if ifconfig -a 2>/dev/null || ifconfig 2>/dev/null || /sbin/ifconfig 2>/dev/null; then
    echo "NET:PASS:ifconfig"
else
    echo "NET:FAIL:ifconfig — command failed"
fi

# Test 3: IPv6 loopback
echo "NET:TEST=ipv6_loopback"
if ifconfig lo0 2>/dev/null | grep -q "inet6" || \
   ifconfig lo0 2>/dev/null | grep -q "inet6" || \
   ifconfig lo 2>/dev/null | grep -q "inet6"; then
    echo "NET:PASS:ipv6_loopback"
elif ping -c 1 ::1 2>/dev/null; then
    echo "NET:PASS:ipv6_loopback_ping"
else
    echo "NET:INFO:ipv6_not_available — INET6 may be disabled"
fi

# Test 4: ping loopback (IPv4)
echo "NET:TEST=ping_loopback"
if ping -c 1 127.0.0.1 2>/dev/null || ping -c 1 localhost 2>/dev/null; then
    echo "NET:PASS:ping_loopback"
else
    echo "NET:FAIL:ping_loopback — ping failed"
fi

# Test 5: e1000/net interface presence (from boot log)
echo "NET:TEST=net_interface"
# Check dmesg for network interface detection
if [ -f /proc/dmesg ]; then
    grep -i "e1000\|eth\|net" /proc/dmesg 2>/dev/null | head -5 && \
        echo "NET:PASS:net_interface_detected" || \
        echo "NET:INFO:no_net_in_dmesg"
elif dmesg 2>/dev/null | grep -qi "e1000\|eth\|net"; then
    echo "NET:PASS:net_interface_detected"
else
    echo "NET:INFO:net_interface — could not check dmesg"
fi

# Test 6: Network stack status
echo "NET:TEST=netstat"
if netstat -rn 2>/dev/null || cat /proc/net/route 2>/dev/null; then
    echo "NET:PASS:netstat_routing"
else
    echo "NET:INFO:netstat — not available or no routing table"
fi

# Test 7: Route to loopback
echo "NET:TEST=route"
if route -n 2>/dev/null | grep -q "127\|lo" || \
   route show 2>/dev/null | grep -q "127\|lo" || \
   netstat -rn 2>/dev/null | grep -q "127\|lo"; then
    echo "NET:PASS:route_loopback"
else
    echo "NET:WARN:route_loopback — no loopback route found"
fi

# Test 8: ping with small packets
echo "NET:TEST=ping_small"
if ping -c 3 -s 56 127.0.0.1 2>/dev/null; then
    echo "NET:PASS:ping_small_packets"
else
    echo "NET:WARN:ping_small — could not verify fragmentation"
fi

# Summary
ELAPSED=$(( $(date +%s 2>/dev/null || echo 0) - START_TIME ))
echo "NET:ELAPSED=${ELAPSED}s"
echo "NET:DONE"
sync
NET_RC
    chmod 755 "$RC_LOCAL"

    IMAGE=$("${SCRIPT_DIR}/scripts/build_test_image.sh" \
        --arch "$ARCH" \
        --rc-local "$RC_LOCAL" \
        --cache \
        --output "${BUILD_DIR}/minix-test-${ARCH}.img" \
        2>&1 | tee "${RESULTS_DIR}/image-build.log" | tail -1)

    if [ -z "$IMAGE" ] || [ ! -f "$IMAGE" ]; then
        echo -e "${RED}Image build failed${NC}"
        exit 1
    fi
    echo -e "${GREEN}Image: ${IMAGE}${NC}"
fi

# ─── Boot in QEMU ───────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[2/2] Booting MINIX in QEMU...${NC}"

QEMU_ARGS=(-nographic -m 512M -smp 1 -no-reboot -serial "file:${SERIAL_OUT}")

# Network configuration
case "$NET_MODE" in
    user)
        QEMU_ARGS+=(-nic user,model=e1000)
        echo -e "${CYAN}Network: user mode (SLiRP NAT)${NC}"
        ;;
    tap)
        QEMU_ARGS+=(-nic tap,ifname=tap0,script=no,downscript=no,model=e1000)
        echo -e "${CYAN}Network: tap mode (needs sudo)${NC}"
        ;;
    isolated)
        QEMU_ARGS+=(-nic none)
        echo -e "${CYAN}Network: isolated (no network)${NC}"
        ;;
    *)
        echo -e "${RED}Unknown mode: ${NET_MODE}${NC}"
        exit 1
        ;;
esac

case "$IMAGE" in
    *.iso)    QEMU_ARGS+=(-cdrom "$IMAGE" -boot order=d) ;;
    *.qcow2)  QEMU_ARGS+=(-drive file="$IMAGE",format=qcow2) ;;
    *)        QEMU_ARGS+=(-drive file="$IMAGE",format=raw) ;;
esac

: > "$SERIAL_OUT"
set +e
timeout "$TIMEOUT" "$QEMU" "${QEMU_ARGS[@]}" 2>&1 | tee -a "$SERIAL_OUT"
QEMU_EXIT=$?
set -e

echo "QEMU exited (code: ${QEMU_EXIT})"

# ─── Analyze results ───────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}Analyzing results...${NC}"

PASS_COUNT=0
FAIL_COUNT=0

# Check for kernel panic
if grep -qi "kernel panic\|KERNEL PANIC" "$SERIAL_OUT" 2>/dev/null; then
    echo -e "${RED}[FAIL] Kernel panic detected${NC}"
    FAIL_COUNT=$((FAIL_COUNT + 1))
fi

# Check for NET:DONE
if grep -q "NET:DONE" "$SERIAL_OUT" 2>/dev/null; then
    echo -e "${GREEN}[PASS] Network test completed${NC}"
    PASS_COUNT=$((PASS_COUNT + 1))
else
    echo -e "${RED}[FAIL] Network test did not complete${NC}"
    FAIL_COUNT=$((FAIL_COUNT + 1))
fi

# Parse structured results
echo ""
echo -e "${CYAN}--- Structured Network Test Results ---${NC}"
while IFS= read -r line; do
    if [[ "$line" == NET:PASS:* ]]; then
        echo -e "  ${GREEN}[PASS] ${line}${NC}"
        PASS_COUNT=$((PASS_COUNT + 1))
    elif [[ "$line" == NET:FAIL:* ]]; then
        echo -e "  ${RED}[FAIL] ${line}${NC}"
        FAIL_COUNT=$((FAIL_COUNT + 1))
    elif [[ "$line" == NET:WARN:* ]]; then
        echo -e "  ${YELLOW}[WARN] ${line}${NC}"
    fi
done < "$SERIAL_OUT"

# ─── Summary ────────────────────────────────────────────────────────────
{
    echo "=========================================="
    echo "QEMU Network Smoke Test Results"
    echo "=========================================="
    echo "Date:         $(date)"
    echo "Architecture: ${ARCH}"
    echo "Image:        ${IMAGE}"
    echo "Mode:         ${NET_MODE}"
    echo "QEMU exit:    ${QEMU_EXIT}"
    echo ""
    echo "Summary: ${PASS_COUNT} passed, ${FAIL_COUNT} failed"
    echo ""
    if [ "$FAIL_COUNT" -gt 0 ]; then
        echo "FAILURES:"
        grep "NET:FAIL:" "$SERIAL_OUT" 2>/dev/null || echo "  (none)"
    fi
    tail -20 "$SERIAL_OUT" 2>/dev/null
} > "$SUMMARY"

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}Tests: ${PASS_COUNT} passed, ${FAIL_COUNT} failed${NC}"
echo -e "${BLUE}========================================${NC}"

[ "$FAIL_COUNT" -le 1 ] || exit 1
exit 0
