#!/usr/bin/env bash
# ============================================================================
# qemu_test_fs.sh — Phase 9.2: QEMU Filesystem Smoke Test
#
# Boots a MINIX test image and tests ext4 filesystem operations:
#   1. ext4 partition detection and mounting
#   2. File create/read/write/delete
#   3. mkfs.ext4 (if available)
#   4. dd read/write test
#   5. fsck (if available)
#
# Usage:
#   ./scripts/qemu_test_fs.sh                         # Build + boot + test
#   ./scripts/qemu_test_fs.sh --image <path>           # Use pre-built image
#   ./scripts/qemu_test_fs.sh --arch aarch64           # ARM64 test
#   ./scripts/qemu_test_fs.sh --timeout 120            # Custom timeout
#   ./scripts/qemu_test_fs.sh --help                   # Show help
#
# Exit codes:
#   0 — All FS tests passed
#   1 — Boot/FS test failure
# ============================================================================

set -euo pipefail

# ─── Colors ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'

# ─── Paths ──────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-${SCRIPT_DIR}/build/qemu-test}"
RESULTS_DIR="${RESULTS_DIR:-$(pwd)/qemu-fs-results}"
SERIAL_OUT="${RESULTS_DIR}/serial.txt"
SUMMARY="${RESULTS_DIR}/summary.txt"

# ─── Defaults ───────────────────────────────────────────────────────────
ARCH="${ARCH:-x86_64}"
IMAGE=""
TIMEOUT=120

# ─── Help ───────────────────────────────────────────────────────────────
usage() {
    cat <<EOF
Usage: $0 [options]

QEMU Filesystem Smoke Test — boots MINIX and tests ext4 operations.

Options:
  --image <path>    Use pre-built test image
  --arch <arch>     Architecture: x86_64 (default) or aarch64
  --timeout <sec>   Boot timeout (default: 120)
  --help            Show this help

Exit codes:
  0 — All tests passed
  1 — Boot/FS test failure

Examples:
  $0                          # Build + boot + test
  $0 --image test.img         # Test with existing image
EOF
    exit 0
}

# ─── Parse arguments ────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --image)   IMAGE="$2"; shift 2 ;;
        --arch)    ARCH="$2"; shift 2 ;;
        --timeout) TIMEOUT="$2"; shift 2 ;;
        --help|-h) usage ;;
        *)         echo "Unknown: $1"; usage ;;
    esac
done

mkdir -p "$RESULTS_DIR"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}QEMU Filesystem Smoke Test${NC}"
echo -e "${BLUE}========================================${NC}"
echo "Architecture: ${ARCH}"
echo "Timeout:      ${TIMEOUT}s"
echo "Results:      ${RESULTS_DIR}"
echo ""

# ─── Check QEMU ─────────────────────────────────────────────────────────
QEMU=""
case "$ARCH" in
    x86_64)  QEMU="qemu-system-x86_64" ;;
    aarch64) QEMU="qemu-system-aarch64" ;;
    *)       echo -e "${RED}Unsupported arch${NC}"; exit 1 ;;
esac
command -v "$QEMU" &>/dev/null || { echo -e "${RED}${QEMU} not found${NC}"; exit 1; }

# ─── Locate or build image ──────────────────────────────────────────────
if [ -n "$IMAGE" ] && [ -f "$IMAGE" ]; then
    echo -e "${GREEN}Using image: ${IMAGE}${NC}"
else
    # Generate rc.local for FS tests
    RC_LOCAL="${RESULTS_DIR}/rc_local.sh"
    cat >"$RC_LOCAL" <<'FS_RC'
#!/bin/sh
# FS smoke test rc.local — generated by qemu_test_fs.sh

echo "FS:START"
START_TIME=$(date +%s 2>/dev/null || echo 0)

# Mount /proc
mount -t procfs none /proc 2>/dev/null || true

# Test 1: List block devices
echo "FS:TEST=block_devices"
if [ -d /dev ]; then
    ls /dev/c0d0* /dev/hd* /dev/sd* 2>/dev/null || echo "FS:INFO:no_block_devices"
    echo "FS:PASS:block_devices_accessible"
else
    echo "FS:FAIL:block_devices — /dev not available"
fi

# Test 2: tmpfs for temp file operations (always available in MINIX)
echo "FS:TEST=tmpfs"
if mount -t tmpfs none /tmp 2>/dev/null; then
    echo "FS:PASS:tmpfs_mount"
else
    # Try ramdisk instead
    mount -t mfs /dev/ram /tmp 2>/dev/null && echo "FS:PASS:tmpfs_mount" || \
        echo "FS:WARN:tmpfs_mount — using /tmp directly"
fi

# Test 3: File create
echo "FS:TEST=file_create"
if touch /tmp/testfile.txt 2>/dev/null; then
    echo "FS:PASS:file_create"
else
    echo "FS:FAIL:file_create — touch failed"
fi

# Test 4: File write (dd)
echo "FS:TEST=file_write"
if dd if=/dev/zero of=/tmp/testfile.bin bs=1024 count=4 2>/dev/null; then
    echo "FS:PASS:file_write"
else
    echo "FS:FAIL:file_write — dd failed"
fi

# Test 5: File read (verify size with wc -c)
echo "FS:TEST=file_read"
if [ -f /tmp/testfile.bin ]; then
    SIZE=$(wc -c < /tmp/testfile.bin 2>/dev/null || echo 0)
    if [ "$SIZE" = "4096" ]; then
        echo "FS:PASS:file_read_correct_size"
    else
        echo "FS:WARN:file_read_size_mismatch (expected 4096, got $SIZE)"
    fi
else
    echo "FS:FAIL:file_read — file not found"
fi

# Test 6: File delete
echo "FS:TEST=file_delete"
if rm /tmp/testfile.bin 2>/dev/null && rm /tmp/testfile.txt 2>/dev/null; then
    echo "FS:PASS:file_delete"
else
    echo "FS:FAIL:file_delete — rm failed"
fi

# Test 7: Directory create/remove
echo "FS:TEST=directory_ops"
if mkdir /tmp/testdir 2>/dev/null && touch /tmp/testdir/file 2>/dev/null && \
   rm /tmp/testdir/file 2>/dev/null && rmdir /tmp/testdir 2>/dev/null; then
    echo "FS:PASS:directory_ops"
else
    echo "FS:FAIL:directory_ops — mkdir/rmdir failed"
fi

# Test 8: ext4 partition (if available)
echo "FS:TEST=ext4_partition"
if mount -t ext4 /dev/c0d0p1 /mnt 2>/dev/null; then
    echo "FS:PASS:ext4_mount"
    ls /mnt/ 2>/dev/null
    touch /mnt/test_ext4.txt 2>/dev/null && echo "FS:PASS:ext4_write" || \
        echo "FS:FAIL:ext4_write"
    rm /mnt/test_ext4.txt 2>/dev/null
    umount /mnt 2>/dev/null
elif mount -t ext4 /dev/hd0 /mnt 2>/dev/null; then
    echo "FS:PASS:ext4_mount_alt"
    umount /mnt 2>/dev/null
else
    echo "FS:INFO:ext4_not_available — no ext4 partition found"
fi

# Test 9: sync
echo "FS:TEST=sync"
if sync 2>/dev/null; then
    echo "FS:PASS:sync"
else
    echo "FS:FAIL:sync"
fi

# Summary
ELAPSED=$(( $(date +%s 2>/dev/null || echo 0) - START_TIME ))
echo "FS:ELAPSED=${ELAPSED}s"
echo "FS:DONE"
sync
FS_RC
    chmod 755 "$RC_LOCAL"

    IMAGE=$("${SCRIPT_DIR}/scripts/build_test_image.sh" \
        --arch "$ARCH" \
        --rc-local "$RC_LOCAL" \
        --cache \
        --output "${BUILD_DIR}/minix-test-${ARCH}.img" \
        2>&1 | tee "${RESULTS_DIR}/image-build.log" | tail -1)

    if [ -z "$IMAGE" ] || [ ! -f "$IMAGE" ]; then
        echo -e "${RED}Image build failed${NC}"
        exit 1
    fi
    echo -e "${GREEN}Image: ${IMAGE}${NC}"
fi

# ─── Boot in QEMU ───────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[2/2] Booting MINIX in QEMU...${NC}"

QEMU_ARGS=(-nographic -m 512M -smp 1 -no-reboot -serial "file:${SERIAL_OUT}")
case "$IMAGE" in
    *.iso)    QEMU_ARGS+=(-cdrom "$IMAGE" -boot order=d) ;;
    *.qcow2)  QEMU_ARGS+=(-drive file="$IMAGE",format=qcow2) ;;
    *)        QEMU_ARGS+=(-drive file="$IMAGE",format=raw) ;;
esac

: > "$SERIAL_OUT"
set +e
timeout "$TIMEOUT" "$QEMU" "${QEMU_ARGS[@]}" 2>&1 | tee -a "$SERIAL_OUT"
QEMU_EXIT=$?
set -e

echo "QEMU exited (code: ${QEMU_EXIT})"

# ─── Analyze results ───────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}Analyzing results...${NC}"

PASS_COUNT=0
FAIL_COUNT=0

# Check for kernel panic
if grep -qi "kernel panic\|KERNEL PANIC\|fatal\|FATAL" "$SERIAL_OUT" 2>/dev/null; then
    echo -e "${RED}[FAIL] Kernel panic detected${NC}"
    grep -i "kernel panic\|KERNEL PANIC\|fatal\|FATAL" "$SERIAL_OUT" 2>/dev/null | head -5
    FAIL_COUNT=$((FAIL_COUNT + 1))
fi

# Check for FS:DONE marker
if grep -q "FS:DONE" "$SERIAL_OUT" 2>/dev/null; then
    echo -e "${GREEN}[PASS] FS test completed${NC}"
    PASS_COUNT=$((PASS_COUNT + 1))
else
    echo -e "${RED}[FAIL] FS test did not complete${NC}"
    FAIL_COUNT=$((FAIL_COUNT + 1))
fi

# Parse structured results
echo ""
echo -e "${CYAN}--- Structured FS Test Results ---${NC}"
while IFS= read -r line; do
    if [[ "$line" == FS:PASS:* ]]; then
        test_name="${line#FS:PASS:}"
        echo -e "  ${GREEN}[PASS] FS: ${test_name}${NC}"
        PASS_COUNT=$((PASS_COUNT + 1))
    elif [[ "$line" == FS:FAIL:* ]]; then
        test_name="${line#FS:FAIL:}"
        echo -e "  ${RED}[FAIL] FS: ${test_name}${NC}"
        FAIL_COUNT=$((FAIL_COUNT + 1))
    elif [[ "$line" == FS:WARN:* ]]; then
        test_name="${line#FS:WARN:}"
        echo -e "  ${YELLOW}[WARN] FS: ${test_name}${NC}"
    fi
done < "$SERIAL_OUT"

# ─── Generate summary ──────────────────────────────────────────────────
{
    echo "=========================================="
    echo "QEMU Filesystem Smoke Test Results"
    echo "=========================================="
    echo "Date:         $(date)"
    echo "Architecture: ${ARCH}"
    echo "Image:        ${IMAGE}"
    echo "QEMU exit:    ${QEMU_EXIT}"
    echo ""
    echo "Summary: ${PASS_COUNT} passed, ${FAIL_COUNT} failed"
    echo ""
    if [ "$FAIL_COUNT" -gt 0 ]; then
        echo "FAILURES:"
        grep "FS:FAIL:" "$SERIAL_OUT" 2>/dev/null || echo "  (none)"
        echo ""
    fi
    echo "Last 20 lines:"
    tail -20 "$SERIAL_OUT" 2>/dev/null
} > "$SUMMARY"

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}Tests: ${PASS_COUNT} passed, ${FAIL_COUNT} failed${NC}"
echo -e "${BLUE}========================================${NC}"

[ "$FAIL_COUNT" -le 1 ] || exit 1
exit 0
