#!/usr/bin/env bash
# ============================================================================
# qemu_test_bt.sh — Phase 9.2: QEMU Bluetooth Smoke Test
#
# Boots a MINIX test image and tests Bluetooth subsystem availability:
#   1. Bluetooth daemon (bluetoothd) presence
#   2. bt-tool status command
#   3. HCI device detection (if available)
#   4. SDP service registration
#
# Usage:
#   ./scripts/qemu_test_bt.sh                          # Build + boot + test
#   ./scripts/qemu_test_bt.sh --image <path>            # Use pre-built image
#   ./scripts/qemu_test_bt.sh --arch aarch64            # ARM64 test
#   ./scripts/qemu_test_bt.sh --timeout 120             # Custom timeout
#   ./scripts/qemu_test_bt.sh --help                    # Show help
#
# Exit codes:
#   0 — All BT tests passed
#   1 — Boot/BT test failure
# ============================================================================

set -euo pipefail

# ─── Colors ─────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'

# ─── Paths ──────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
BUILD_DIR="${BUILD_DIR:-${SCRIPT_DIR}/build/qemu-test}"
RESULTS_DIR="${RESULTS_DIR:-$(pwd)/qemu-bt-results}"
SERIAL_OUT="${RESULTS_DIR}/serial.txt"
SUMMARY="${RESULTS_DIR}/summary.txt"

# ─── Defaults ───────────────────────────────────────────────────────────
ARCH="${ARCH:-x86_64}"
IMAGE=""
TIMEOUT=120

# ─── Help ───────────────────────────────────────────────────────────────
usage() {
    cat <<EOF
Usage: $0 [options]

QEMU Bluetooth Smoke Test — boots MINIX and tests BT subsystem.

Options:
  --image <path>    Use pre-built test image
  --arch <arch>     Architecture: x86_64 (default) or aarch64
  --timeout <sec>   Boot timeout (default: 120)
  --help            Show this help

Exit codes:
  0 — All tests passed
  1 — Boot/BT test failure

Examples:
  $0                          # Build + boot + test
  $0 --image test.img         # Test with existing image
EOF
    exit 0
}

# ─── Parse arguments ────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --image)   IMAGE="$2"; shift 2 ;;
        --arch)    ARCH="$2"; shift 2 ;;
        --timeout) TIMEOUT="$2"; shift 2 ;;
        --help|-h) usage ;;
        *)         echo "Unknown: $1"; usage ;;
    esac
done

mkdir -p "$RESULTS_DIR"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}QEMU Bluetooth Smoke Test${NC}"
echo -e "${BLUE}========================================${NC}"
echo "Architecture: ${ARCH}"
echo "Timeout:      ${TIMEOUT}s"
echo "Results:      ${RESULTS_DIR}"
echo ""

# ─── Check QEMU ─────────────────────────────────────────────────────────
QEMU=""
case "$ARCH" in
    x86_64)  QEMU="qemu-system-x86_64" ;;
    aarch64) QEMU="qemu-system-aarch64" ;;
    *)       echo -e "${RED}Unsupported arch${NC}"; exit 1 ;;
esac
command -v "$QEMU" &>/dev/null || { echo -e "${RED}${QEMU} not found${NC}"; exit 1; }

# ─── Locate or build image ──────────────────────────────────────────────
if [ -n "$IMAGE" ] && [ -f "$IMAGE" ]; then
    echo -e "${GREEN}Using image: ${IMAGE}${NC}"
else
    RC_LOCAL="${RESULTS_DIR}/rc_local.sh"
    cat >"$RC_LOCAL" <<'BT_RC'
#!/bin/sh
# Bluetooth smoke test rc.local — generated by qemu_test_bt.sh

echo "BT:START"
START_TIME=$(date +%s 2>/dev/null || echo 0)

# Mount /proc
mount -t procfs none /proc 2>/dev/null || true

# Test 1: Check if bluetoothd is present in the filesystem
echo "BT:TEST=bluetoothd_presence"
if [ -f /sbin/bluetoothd ] || [ -f /usr/sbin/bluetoothd ]; then
    echo "BT:PASS:bluetoothd_present"
    BT_DAEMON=$(ls /sbin/bluetoothd /usr/sbin/bluetoothd 2>/dev/null | head -1)
    echo "BT:INFO:bluetoothd at ${BT_DAEMON}"
elif command -v bluetoothd 2>/dev/null; then
    echo "BT:PASS:bluetoothd_in_path"
else
    echo "BT:INFO:bluetoothd_not_found — BT daemon not built into this image"
fi

# Test 2: Check bt-tool presence
echo "BT:TEST=bt_tool_presence"
if command -v bt-tool 2>/dev/null || [ -f /sbin/bt-tool ] || [ -f /usr/sbin/bt-tool ]; then
    echo "BT:PASS:bt_tool_present"
else
    echo "BT:INFO:bt_tool_not_found — bt-tool not built into this image"
fi

# Test 3: Run bt-tool status (if available)
echo "BT:TEST=bt_tool_status"
if command -v bt-tool 2>/dev/null; then
    if bt-tool status 2>/dev/null; then
        echo "BT:PASS:bt_tool_status"
    else
        echo "BT:FAIL:bt_tool_status — command returned error"
    fi
elif [ -f /sbin/bt-tool ]; then
    if /sbin/bt-tool status 2>/dev/null; then
        echo "BT:PASS:bt_tool_status"
    else
        echo "BT:FAIL:bt_tool_status — command returned error"
    fi
else
    echo "BT:INFO:bt_tool_status — bt-tool not available"
fi

# Test 4: Check for HCI device in /proc or /dev
echo "BT:TEST=hci_device"
if [ -d /proc/bluetooth ] || [ -d /sys/class/bluetooth ]; then
    echo "BT:PASS:hci_subsystem"
    ls /proc/bluetooth/ 2>/dev/null || ls /sys/class/bluetooth/ 2>/dev/null
elif [ -c /dev/hci0 ] || [ -c /dev/hci ]; then
    echo "BT:PASS:hci_device_node"
else
    echo "BT:INFO:hci_device — no HCI device (expected: needs USB HCI or emulation)"
fi

# Test 5: Bluetooth libraries presence
echo "BT:TEST=bt_libraries"
if [ -f /usr/lib/libbluetooth.so ] || [ -f /lib/libbluetooth.so ]; then
    echo "BT:PASS:bt_libraries_present"
else
    echo "BT:INFO:bt_libraries — libbluetooth.so not in this image"
fi

# Test 6: Check if Bluetooth was mentioned in boot log
echo "BT:TEST=bt_boot_log"
if dmesg 2>/dev/null | grep -qi "bluetooth\|hci\|bt\|blue"; then
    echo "BT:PASS:bt_boot_log_detected"
    dmesg 2>/dev/null | grep -i "bluetooth\|hci\|bt" | head -5
else
    echo "BT:INFO:bt_boot_log — no BLUETOOTH in boot log (expected without HW)"
fi

# Test 7: Start bluetoothd if present
echo "BT:TEST=bluetoothd_start"
if [ -f /sbin/bluetoothd ] && command -v bt-tool 2>/dev/null; then
    /sbin/bluetoothd &
    BT_PID=$!
    sleep 2
    if kill -0 $BT_PID 2>/dev/null; then
        echo "BT:PASS:bluetoothd_started"
        # Now run status to verify daemon responds
        bt-tool status 2>/dev/null && echo "BT:PASS:bt_tool_status_via_daemon" || \
            echo "BT:WARN:bt_tool_status_via_daemon — no response"
        kill $BT_PID 2>/dev/null || true
    else
        echo "BT:WARN:bluetoothd_start — daemon exited immediately"
    fi
else
    echo "BT:INFO:bluetoothd_start — skipped (no bluetoothd in image)"
fi

# Summary
ELAPSED=$(( $(date +%s 2>/dev/null || echo 0) - START_TIME ))
echo "BT:ELAPSED=${ELAPSED}s"
echo "BT:DONE"
sync
BT_RC
    chmod 755 "$RC_LOCAL"

    IMAGE=$("${SCRIPT_DIR}/scripts/build_test_image.sh" \
        --arch "$ARCH" \
        --rc-local "$RC_LOCAL" \
        --cache \
        --output "${BUILD_DIR}/minix-test-${ARCH}.img" \
        2>&1 | tee "${RESULTS_DIR}/image-build.log" | tail -1)

    if [ -z "$IMAGE" ] || [ ! -f "$IMAGE" ]; then
        echo -e "${RED}Image build failed${NC}"
        exit 1
    fi
    echo -e "${GREEN}Image: ${IMAGE}${NC}"
fi

# ─── Boot in QEMU ───────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[2/2] Booting MINIX in QEMU...${NC}"

QEMU_ARGS=(-nographic -m 512M -smp 1 -no-reboot -serial "file:${SERIAL_OUT}")
case "$IMAGE" in
    *.iso)    QEMU_ARGS+=(-cdrom "$IMAGE" -boot order=d) ;;
    *.qcow2)  QEMU_ARGS+=(-drive file="$IMAGE",format=qcow2) ;;
    *)        QEMU_ARGS+=(-drive file="$IMAGE",format=raw) ;;
esac

: > "$SERIAL_OUT"
set +e
timeout "$TIMEOUT" "$QEMU" "${QEMU_ARGS[@]}" 2>&1 | tee -a "$SERIAL_OUT"
QEMU_EXIT=$?
set -e

echo "QEMU exited (code: ${QEMU_EXIT})"

# ─── Analyze results ───────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}Analyzing results...${NC}"

PASS_COUNT=0
FAIL_COUNT=0

# Check for kernel panic
if grep -qi "kernel panic\|KERNEL PANIC" "$SERIAL_OUT" 2>/dev/null; then
    echo -e "${RED}[FAIL] Kernel panic detected${NC}"
    FAIL_COUNT=$((FAIL_COUNT + 1))
fi

# Check for BT:DONE
if grep -q "BT:DONE" "$SERIAL_OUT" 2>/dev/null; then
    echo -e "${GREEN}[PASS] BT test completed${NC}"
    PASS_COUNT=$((PASS_COUNT + 1))
else
    echo -e "${RED}[FAIL] BT test did not complete${NC}"
    FAIL_COUNT=$((FAIL_COUNT + 1))
fi

# Parse structured results
echo ""
echo -e "${CYAN}--- Structured Bluetooth Test Results ---${NC}"
while IFS= read -r line; do
    if [[ "$line" == BT:PASS:* ]]; then
        echo -e "  ${GREEN}[PASS] ${line}${NC}"
        PASS_COUNT=$((PASS_COUNT + 1))
    elif [[ "$line" == BT:FAIL:* ]]; then
        echo -e "  ${RED}[FAIL] ${line}${NC}"
        FAIL_COUNT=$((FAIL_COUNT + 1))
    elif [[ "$line" == BT:WARN:* ]]; then
        echo -e "  ${YELLOW}[WARN] ${line}${NC}"
    fi
done < "$SERIAL_OUT"

# ─── Summary ────────────────────────────────────────────────────────────
{
    echo "=========================================="
    echo "QEMU Bluetooth Smoke Test Results"
    echo "=========================================="
    echo "Date:         $(date)"
    echo "Architecture: ${ARCH}"
    echo "Image:        ${IMAGE}"
    echo "QEMU exit:    ${QEMU_EXIT}"
    echo ""
    echo "Summary: ${PASS_COUNT} passed, ${FAIL_COUNT} failed"
    echo ""
    if [ "$FAIL_COUNT" -gt 0 ]; then
        echo "FAILURES:"
        grep "BT:FAIL:" "$SERIAL_OUT" 2>/dev/null || echo "  (none)"
    fi
    tail -20 "$SERIAL_OUT" 2>/dev/null
} > "$SUMMARY"

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}Tests: ${PASS_COUNT} passed, ${FAIL_COUNT} failed${NC}"
echo -e "${BLUE}========================================${NC}"

[ "$FAIL_COUNT" -le 1 ] || exit 1
exit 0
