/* ============================================================
 * fdt.c — Flattened Device Tree Blob parser for AArch64 boot
 *
 * Minimal self-contained DTB parser for early kernel bootstrap.
 * Parses the Device Tree provided by the bootloader to extract
 * memory layout, CPU count, boot arguments, and console info.
 *
 * All functions in this file are placed in .unpaged.text so they
 * are accessible from the early boot context (identity-mapped
 * region) before the high kernel mapping at KERNEL_VBASE is set up.
 *
 * All multi-byte values in the DTB are big-endian; this parser
 * converts them to little-endian on access.
 *
 * Node traversal is linear (not a real tree walker) — sufficient
 * for the small DTBs generated by QEMU virt and U-Boot.
 *
 * Phase 3: FDT parser for AArch64 MINIX boot
 * ============================================================ */

#include "fdt.h"
#include <stddef.h>

/* Macro to place a function in the unpaged section
 * (identity-mapped at PHYS_BASE, accessible during early boot).
 */
#define UNPAGED __attribute__((section(".unpaged.text")))

/* =========================================================================
 * Internal helpers (all inlined — no separate section needed)
 * ========================================================================= */

/* Get a pointer to the header as a struct fdt_header */
static inline const struct fdt_header *
fdt_header(const void *fdt)
{
    return (const struct fdt_header *)fdt;
}

/* Get the start of the structure block */
static inline const uint32_t *
fdt_struct_start(const void *fdt)
{
    const struct fdt_header *hdr = fdt_header(fdt);
    return (const uint32_t *)((const uint8_t *)fdt +
                              fdt32_to_cpu(&hdr->off_dt_struct));
}

/* Get the start of the strings block */
static inline const char *
fdt_strings_start(const void *fdt)
{
    const struct fdt_header *hdr = fdt_header(fdt);
    return (const char *)fdt + fdt32_to_cpu(&hdr->off_dt_strings);
}

/* Get the string at a given offset in the strings block */
static inline const char *
fdt_string(const void *fdt, uint32_t off)
{
    return fdt_strings_start(fdt) + off;
}

/* Round a value up to the next 4-byte boundary */
static inline uint32_t
fdt_round_up4(uint32_t v)
{
    return (v + 3) & ~3U;
}

/* =========================================================================
 * Public API
 * ========================================================================= */

UNPAGED int
fdt_validate(const void *fdt, uint32_t size)
{
    uint32_t magic;

    if (!fdt)
        return -1;

    magic = fdt32_to_cpu(&fdt_header(fdt)->magic);
    if (magic != 0xD00DFEED)
        return -1;

    if (size > 0 && fdt32_to_cpu(&fdt_header(fdt)->totalsize) > size)
        return -1;

    return 0;
}

UNPAGED uint32_t
fdt_total_size(const void *fdt)
{
    if (!fdt)
        return 0;
    return fdt32_to_cpu(&fdt_header(fdt)->totalsize);
}

/* =========================================================================
 * Node iterator
 *
 * Walks the structure block linearly, calling a callback for each
 * node/property. Used internally by the higher-level parsing functions.
 * ========================================================================= */

/* Callback return values */
#define FDT_WALK_CONTINUE   0   /* Continue walking */
#define FDT_WALK_STOP       1   /* Stop walking (found what we need) */

/* Node depth context for the walker */
struct fdt_walk_ctx {
    int depth;                     /* Current node depth (0 = root) */
    const char *current_node;      /* Name of current node */
    int current_node_len;          /* Length of current node name */
    /* Property context */
    const char *prop_name;         /* Name of current property (NULL if not in prop) */
    uint32_t prop_len;             /* Length of property value */
    const uint8_t *prop_data;      /* Pointer to property value data */
};

/*
 * Walk the DTB structure block. For each node and property, calls
 * the provided callbacks.
 *
 * on_node_begin: called at FDT_BEGIN_NODE, before processing children.
 *                Return FDT_WALK_STOP to skip children.
 * on_node_end:   called at FDT_END_NODE (after children processed).
 * on_prop:       called for each FDT_PROP within a node.
 *                Return FDT_WALK_STOP to skip remaining properties.
 */
UNPAGED static void
fdt_walk(const void *fdt,
         int (*on_node_begin)(struct fdt_walk_ctx *ctx, void *arg),
         int (*on_node_end)(struct fdt_walk_ctx *ctx, void *arg),
         int (*on_prop)(struct fdt_walk_ctx *ctx, void *arg),
         void *arg)
{
    const uint32_t *p = fdt_struct_start(fdt);
    const uint8_t *end = (const uint8_t *)p +
                         fdt32_to_cpu(&fdt_header(fdt)->size_dt_struct);
    struct fdt_walk_ctx ctx;
    uint32_t token;
    int rc;

    /* Depth starts at -1 so the first BEGIN_NODE (root) puts us at depth 0.
     * This means: root = 0, children of root = 1, grandchildren = 2, etc.
     * All callbacks use this convention for matching. */
    ctx.depth = -1;
    ctx.current_node = NULL;
    ctx.current_node_len = 0;
    ctx.prop_name = NULL;
    ctx.prop_len = 0;
    ctx.prop_data = NULL;

    while ((const uint8_t *)p < end) {
        token = fdt32_to_cpu(p);
        p++;

        switch (token) {
        case FDT_TOKEN_BEGIN_NODE: {
            const char *name = (const char *)p;
            uint32_t name_len = 0;

            while (name[name_len] != '\0' && name_len < 256)
                name_len++;
            p += (name_len + 1 + 3) / 4;

            ctx.depth++;
            ctx.current_node = name;
            ctx.current_node_len = name_len;
            ctx.prop_name = NULL;
            ctx.prop_len = 0;
            ctx.prop_data = NULL;

            if (on_node_begin) {
                rc = on_node_begin(&ctx, arg);
                if (rc == FDT_WALK_STOP) {
                    int skip_depth = ctx.depth;
                    while ((const uint8_t *)p < end && ctx.depth >= skip_depth) {
                        token = fdt32_to_cpu(p);
                        p++;
                        switch (token) {
                        case FDT_TOKEN_BEGIN_NODE: ctx.depth++; break;
                        case FDT_TOKEN_END_NODE:   ctx.depth--; break;
                        case FDT_TOKEN_PROP: {
                            const struct fdt_prop_header *ph =
                                (const struct fdt_prop_header *)p;
                            uint32_t plen = fdt32_to_cpu(&ph->len);
                            p += 2 + (fdt_round_up4(plen) / 4);
                            break;
                        }
                        case FDT_TOKEN_NOP: break;
                        case FDT_TOKEN_END: return;
                        }
                    }
                }
            }
            break;
        }

        case FDT_TOKEN_END_NODE: {
            if (on_node_end) {
                rc = on_node_end(&ctx, arg);
                if (rc == FDT_WALK_STOP) return;
            }
            ctx.depth--;
            break;
        }

        case FDT_TOKEN_PROP: {
            const struct fdt_prop_header *ph =
                (const struct fdt_prop_header *)p;
            uint32_t plen = fdt32_to_cpu(&ph->len);
            uint32_t name_off = fdt32_to_cpu(&ph->nameoff);

            ctx.prop_name = fdt_string(fdt, name_off);
            ctx.prop_len = plen;
            ctx.prop_data = (const uint8_t *)(ph + 1);

            if (on_prop) {
                rc = on_prop(&ctx, arg);
                if (rc == FDT_WALK_STOP) return;
            }

            p += 2 + (fdt_round_up4(plen) / 4);
            break;
        }

        case FDT_TOKEN_NOP: break;
        case FDT_TOKEN_END: return;
        default: break;
        }
    }
}

/* =========================================================================
 * Read big-endian cells
 * ========================================================================= */

static inline uint64_t
read_cells(const uint32_t *p, int cells)
{
    uint64_t val = 0;
    int i;
    for (i = 0; i < cells; i++)
        val = (val << 32) | fdt32_to_cpu(p + i);
    return val;
}

/* =========================================================================
 * Memory parsing
 * ========================================================================= */

struct mem_ctx {
    uint64_t reg_addr, reg_size;
    int found;
    int addr_cells, size_cells;
    int in_memory;
    int in_root;
};

UNPAGED static int
memory_on_node_begin(struct fdt_walk_ctx *ctx, void *arg)
{
    struct mem_ctx *mc = (struct mem_ctx *)arg;
    if (mc->in_root && ctx->depth == 1) {
        const char *n = ctx->current_node;
        if (n[0]=='m'&&n[1]=='e'&&n[2]=='m'&&n[3]=='o'&&n[4]=='r'&&n[5]=='y') {
            mc->in_memory = 1;
        }
    }
    return FDT_WALK_CONTINUE;
}

UNPAGED static int
memory_on_prop(struct fdt_walk_ctx *ctx, void *arg)
{
    struct mem_ctx *mc = (struct mem_ctx *)arg;
    if (!mc->in_memory) return FDT_WALK_CONTINUE;

    if (ctx->prop_name[0]=='d'&&ctx->prop_name[1]=='e'&&ctx->prop_name[2]=='v'&&
        ctx->prop_name[3]=='i'&&ctx->prop_name[4]=='c'&&ctx->prop_name[5]=='e'&&
        ctx->prop_name[6]=='_'&&ctx->prop_name[7]=='t'&&ctx->prop_name[8]=='y'&&
        ctx->prop_name[9]=='p'&&ctx->prop_name[10]=='e'&&ctx->prop_name[11]=='\0') {
        return FDT_WALK_CONTINUE;
    }

    if (ctx->prop_name[0]=='r'&&ctx->prop_name[1]=='e'&&
        ctx->prop_name[2]=='g'&&ctx->prop_name[3]=='\0') {
        int tc = mc->addr_cells + mc->size_cells;
        if (tc > 0 && ctx->prop_len >= (uint32_t)(tc * 4)) {
            const uint32_t *d = (const uint32_t *)ctx->prop_data;
            mc->reg_addr = read_cells(d, mc->addr_cells);
            mc->reg_size = read_cells(d + mc->addr_cells, mc->size_cells);
            mc->found = 1;
            return FDT_WALK_STOP;
        }
    }
    return FDT_WALK_CONTINUE;
}

UNPAGED static int
memory_on_node_end(struct fdt_walk_ctx *ctx, void *arg)
{
    struct mem_ctx *mc = (struct mem_ctx *)arg;
    if (mc->in_memory && ctx->depth == 1) mc->in_memory = 0;
    return FDT_WALK_CONTINUE;
}

UNPAGED static int
root_on_prop(struct fdt_walk_ctx *ctx, void *arg)
{
    struct mem_ctx *mc = (struct mem_ctx *)arg;
    if (ctx->depth != 0) return FDT_WALK_CONTINUE;

    if (ctx->prop_name[0]=='#'&&ctx->prop_name[1]=='a'&&ctx->prop_name[2]=='d'&&
        ctx->prop_name[3]=='d'&&ctx->prop_name[4]=='r'&&ctx->prop_name[5]=='e'&&
        ctx->prop_name[6]=='s'&&ctx->prop_name[7]=='s'&&ctx->prop_name[8]=='-'&&
        ctx->prop_name[9]=='c'&&ctx->prop_name[10]=='e'&&ctx->prop_name[11]=='l'&&
        ctx->prop_name[12]=='l'&&ctx->prop_name[13]=='s'&&ctx->prop_name[14]=='\0') {
        if (ctx->prop_len >= 4)
            mc->addr_cells = (int)fdt32_to_cpu((const uint32_t *)ctx->prop_data);
    }
    if (ctx->prop_name[0]=='#'&&ctx->prop_name[1]=='s'&&ctx->prop_name[2]=='i'&&
        ctx->prop_name[3]=='z'&&ctx->prop_name[4]=='e'&&ctx->prop_name[5]=='-'&&
        ctx->prop_name[6]=='c'&&ctx->prop_name[7]=='e'&&ctx->prop_name[8]=='l'&&
        ctx->prop_name[9]=='l'&&ctx->prop_name[10]=='s'&&ctx->prop_name[11]=='\0') {
        if (ctx->prop_len >= 4)
            mc->size_cells = (int)fdt32_to_cpu((const uint32_t *)ctx->prop_data);
    }
    return FDT_WALK_CONTINUE;
}

UNPAGED int
fdt_get_memory(const void *fdt, uint64_t *reg_addr, uint64_t *reg_size)
{
    struct mem_ctx mc;
    if (!fdt || !reg_addr || !reg_size) return -1;

    mc.reg_addr = 0; mc.reg_size = 0; mc.found = 0;
    mc.addr_cells = 2; mc.size_cells = 2;
    mc.in_memory = 0; mc.in_root = 1;

    {
        struct mem_ctx rm;
        rm.addr_cells = 2; rm.size_cells = 2;
        rm.depth = 0;
        fdt_walk(fdt, NULL, NULL, root_on_prop, &rm);
        mc.addr_cells = rm.addr_cells;
        mc.size_cells = rm.size_cells;
    }

    fdt_walk(fdt, memory_on_node_begin, memory_on_node_end,
             memory_on_prop, &mc);

    if (mc.found) {
        *reg_addr = mc.reg_addr;
        *reg_size = mc.reg_size;
        return 1;
    }
    return 0;
}

/* =========================================================================
 * CPU count parsing
 * ========================================================================= */

struct cpu_ctx { int count; int in_cpus; };

UNPAGED static int
cpus_on_node_begin(struct fdt_walk_ctx *ctx, void *arg)
{
    struct cpu_ctx *cc = (struct cpu_ctx *)arg;
    const char *n = ctx->current_node;
    if (ctx->depth == 1 && n[0]=='c'&&n[1]=='p'&&n[2]=='u'&&n[3]=='s'&&
        (n[4]=='\0'||n[4]=='@')) {
        cc->in_cpus = 1;
    } else if (ctx->depth == 2 && cc->in_cpus &&
               n[0]=='c'&&n[1]=='p'&&n[2]=='u'&&(n[3]=='\0'||n[3]=='@')) {
        cc->count++;
    }
    return FDT_WALK_CONTINUE;
}

UNPAGED static int
cpus_on_node_end(struct fdt_walk_ctx *ctx, void *arg)
{
    struct cpu_ctx *cc = (struct cpu_ctx *)arg;
    if (cc->in_cpus && ctx->depth == 1) cc->in_cpus = 0;
    return FDT_WALK_CONTINUE;
}

UNPAGED int
fdt_get_cpu_count(const void *fdt)
{
    struct cpu_ctx cc;
    if (!fdt) return 0;
    cc.count = 0; cc.in_cpus = 0;
    fdt_walk(fdt, cpus_on_node_begin, cpus_on_node_end, NULL, &cc);
    return cc.count;
}

/* =========================================================================
 * Chosen node parsing
 * ========================================================================= */

struct chosen_ctx { const char *bootargs, *stdout_path; int in_chosen; };

UNPAGED static int
chosen_on_node_begin(struct fdt_walk_ctx *ctx, void *arg)
{
    struct chosen_ctx *cc = (struct chosen_ctx *)arg;
    if (ctx->depth == 1) {
        const char *n = ctx->current_node;
        if (n[0]=='c'&&n[1]=='h'&&n[2]=='o'&&n[3]=='s'&&n[4]=='e'&&n[5]=='n'&&
            (n[6]=='\0'||n[6]=='@')) cc->in_chosen = 1;
    }
    return FDT_WALK_CONTINUE;
}

UNPAGED static int
chosen_on_prop(struct fdt_walk_ctx *ctx, void *arg)
{
    struct chosen_ctx *cc = (struct chosen_ctx *)arg;
    if (!cc->in_chosen) return FDT_WALK_CONTINUE;

    if (ctx->prop_name[0]=='b'&&ctx->prop_name[1]=='o'&&ctx->prop_name[2]=='o'&&
        ctx->prop_name[3]=='t'&&ctx->prop_name[4]=='a'&&ctx->prop_name[5]=='r'&&
        ctx->prop_name[6]=='g'&&ctx->prop_name[7]=='s'&&ctx->prop_name[8]=='\0') {
        if (ctx->prop_len > 0 && ctx->prop_data[0] != '\0')
            cc->bootargs = (const char *)ctx->prop_data;
    }

    if (ctx->prop_name[0]=='s'&&ctx->prop_name[1]=='t'&&ctx->prop_name[2]=='d'&&
        ctx->prop_name[3]=='o'&&ctx->prop_name[4]=='u'&&ctx->prop_name[5]=='t'&&
        ctx->prop_name[6]=='-'&&ctx->prop_name[7]=='p'&&ctx->prop_name[8]=='a'&&
        ctx->prop_name[9]=='t'&&ctx->prop_name[10]=='h'&&ctx->prop_name[11]=='\0') {
        if (ctx->prop_len > 0 && ctx->prop_data[0] != '\0')
            cc->stdout_path = (const char *)ctx->prop_data;
    }

    return FDT_WALK_CONTINUE;
}

UNPAGED static int
chosen_on_node_end(struct fdt_walk_ctx *ctx, void *arg)
{
    struct chosen_ctx *cc = (struct chosen_ctx *)arg;
    if (cc->in_chosen && ctx->depth == 1) {
        cc->in_chosen = 0;
        return FDT_WALK_STOP;
    }
    return FDT_WALK_CONTINUE;
}

UNPAGED const char *
fdt_get_chosen_bootargs(const void *fdt)
{
    struct chosen_ctx cc;
    if (!fdt) return NULL;
    cc.bootargs = NULL; cc.stdout_path = NULL; cc.in_chosen = 0;
    fdt_walk(fdt, chosen_on_node_begin, chosen_on_node_end,
             chosen_on_prop, &cc);
    return cc.bootargs;
}

UNPAGED const char *
fdt_get_chosen_stdout(const void *fdt)
{
    struct chosen_ctx cc;
    if (!fdt) return NULL;
    cc.bootargs = NULL; cc.stdout_path = NULL; cc.in_chosen = 0;
    fdt_walk(fdt, chosen_on_node_begin, chosen_on_node_end,
             chosen_on_prop, &cc);
    return cc.stdout_path;
}

/* =========================================================================
 * Path/alias resolution helpers
 * ========================================================================= */

UNPAGED static void
fdt_strip_stdout_options(const char *sp, char *buf, int max_len)
{
    int i = 0;
    while (sp[i] != '\0' && sp[i] != ':' && i < max_len - 1) {
        buf[i] = sp[i];
        i++;
    }
    buf[i] = '\0';
}

/* =========================================================================
 * fdt_resolve_alias — resolve alias via /aliases node
 * ========================================================================= */

struct alias_ctx {
    const char *alias_name;
    int alias_len;
    char *resolved;
    int max_len, resolved_len;
    int in_aliases, done;
};

UNPAGED static int
alias_on_node_begin(struct fdt_walk_ctx *ctx, void *arg)
{
    struct alias_ctx *ac = (struct alias_ctx *)arg;
    if (ctx->depth == 1) {
        const char *n = ctx->current_node;
        if (n[0]=='a'&&n[1]=='l'&&n[2]=='i'&&n[3]=='a'&&
            n[4]=='s'&&n[5]=='e'&&n[6]=='s'&&(n[7]=='\0'||n[7]=='@'))
            ac->in_aliases = 1;
    }
    return FDT_WALK_CONTINUE;
}

UNPAGED static int
alias_on_prop(struct fdt_walk_ctx *ctx, void *arg)
{
    struct alias_ctx *ac = (struct alias_ctx *)arg;
    if (!ac->in_aliases || ac->done) return FDT_WALK_CONTINUE;

    int i;
    for (i = 0; i < ac->alias_len; i++)
        if (ctx->prop_name[i] != ac->alias_name[i])
            return FDT_WALK_CONTINUE;
    if (ctx->prop_name[ac->alias_len] != '\0')
        return FDT_WALK_CONTINUE;

    int copy_len = (int)ctx->prop_len;
    if (copy_len > ac->max_len - 1) copy_len = ac->max_len - 1;
    for (i = 0; i < copy_len; i++)
        ac->resolved[i] = (char)ctx->prop_data[i];
    ac->resolved[copy_len] = '\0';
    ac->resolved_len = copy_len;
    ac->done = 1;
    return FDT_WALK_STOP;
}

UNPAGED static int
alias_on_node_end(struct fdt_walk_ctx *ctx, void *arg)
{
    struct alias_ctx *ac = (struct alias_ctx *)arg;
    if (ac->in_aliases && ctx->depth == 1) {
        ac->in_aliases = 0;
        return FDT_WALK_STOP;
    }
    return FDT_WALK_CONTINUE;
}

UNPAGED int
fdt_resolve_alias(const void *fdt, const char *alias,
                  char *resolved, int max_len)
{
    struct alias_ctx ac;
    if (!fdt || !alias || !resolved || max_len <= 0) return -1;

    ac.alias_len = 0;
    while (alias[ac.alias_len] != '\0') ac.alias_len++;

    ac.alias_name = alias;
    ac.resolved = resolved;
    ac.max_len = max_len;
    ac.resolved_len = -1;
    ac.in_aliases = 0;
    ac.done = 0;

    fdt_walk(fdt, alias_on_node_begin, alias_on_node_end,
             alias_on_prop, &ac);
    return ac.done ? ac.resolved_len : -1;
}

/* =========================================================================
 * fdt_get_node_reg — get reg property of a node at a given path
 *
 * Walks the DTB to find the node at @path, auto-detects
 * #address-cells and #size-cells from the parent, and extracts
 * the first reg entry.
 * ========================================================================= */

struct node_path_ctx {
    const char *path;              /* Path string to follow */
    int num_components;            /* Number of path components */

    int known_cells;               /* Are cells from caller? */
    int addr_cells, size_cells;    /* #address-cells/#size-cells */

    int target_depth;              /* Depth of target node */
    int in_target;                 /* Currently inside target node */

    uint64_t reg_addr, reg_size;   /* Result */
    int found;
};

UNPAGED static const char *
fdt_path_component(const char *path, int n, int *out_len)
{
    if (*path == '/') path++;
    int comp = 0;
    while (*path != '\0') {
        if (comp == n) {
            const char *start = path;
            int len = 0;
            while (path[len] != '\0' && path[len] != '/') len++;
            *out_len = len;
            return start;
        }
        while (*path != '\0' && *path != '/') path++;
        if (*path == '/') { path++; comp++; }
    }
    *out_len = 0;
    return NULL;
}

UNPAGED static int
fdt_path_num_components(const char *path)
{
    if (*path == '/') path++;
    int count = 0;
    while (*path != '\0') {
        count++;
        while (*path != '\0' && *path != '/') path++;
        if (*path == '/') path++;
    }
    return count;
}

/* Match a node name against a path component (length-based).
 * Small enough to inline — avoids a separate .text section entry. */
static inline int
name_matches(const char *node_name, const char *comp, int comp_len)
{
    int i;
    for (i = 0; i < comp_len; i++) {
        if (node_name[i] == '\0' || node_name[i] == '@') break;
        if (node_name[i] != comp[i]) return 0;
    }

    /* Check if comp contains '@' (unit address) */
    int has_at = 0;
    for (i = 0; i < comp_len; i++)
        if (comp[i] == '@') { has_at = 1; break; }

    if (has_at) {
        for (i = 0; i < comp_len; i++)
            if (node_name[i] != comp[i]) return 0;
        return (node_name[comp_len] == '\0' || node_name[comp_len] == '@');
    }

    /* No '@': match base name only */
    int base_len = 0;
    while (node_name[base_len] != '\0' && node_name[base_len] != '@')
        base_len++;
    return (comp_len == base_len);
}

UNPAGED static int
np_on_node_begin(struct fdt_walk_ctx *ctx, void *arg)
{
    struct node_path_ctx *nc = (struct node_path_ctx *)arg;
    int comp_idx = ctx->depth - 1;

    if (comp_idx < 0) return FDT_WALK_CONTINUE;
    if (comp_idx >= nc->num_components) return FDT_WALK_STOP;

    int comp_len;
    const char *comp = fdt_path_component(nc->path, comp_idx, &comp_len);
    if (!comp) return FDT_WALK_STOP;

    if (!name_matches(ctx->current_node, comp, comp_len))
        return FDT_WALK_STOP;

    if (comp_idx == nc->num_components - 1) {
        nc->in_target = 1;
        nc->target_depth = ctx->depth;
    }
    return FDT_WALK_CONTINUE;
}

UNPAGED static int
np_on_node_end(struct fdt_walk_ctx *ctx, void *arg)
{
    struct node_path_ctx *nc = (struct node_path_ctx *)arg;
    if (nc->in_target && ctx->depth == nc->target_depth)
        nc->in_target = 0;
    return FDT_WALK_CONTINUE;
}

UNPAGED static int
np_on_prop(struct fdt_walk_ctx *ctx, void *arg)
{
    struct node_path_ctx *nc = (struct node_path_ctx *)arg;

    /* Capture #address-cells / #size-cells from parent node */
    if (!nc->known_cells && !nc->in_target &&
        ctx->depth == nc->target_depth - 1 && nc->target_depth > 0) {
        if (ctx->prop_name[0]=='#'&&ctx->prop_name[1]=='a'&&
            ctx->prop_name[2]=='d'&&ctx->prop_name[3]=='d'&&
            ctx->prop_name[4]=='r'&&ctx->prop_name[5]=='e'&&
            ctx->prop_name[6]=='s'&&ctx->prop_name[7]=='s'&&
            ctx->prop_name[8]=='-'&&ctx->prop_name[9]=='c'&&
            ctx->prop_name[10]=='e'&&ctx->prop_name[11]=='l'&&
            ctx->prop_name[12]=='l'&&ctx->prop_name[13]=='s'&&
            ctx->prop_name[14]=='\0' && ctx->prop_len >= 4) {
            nc->addr_cells = (int)fdt32_to_cpu(
                (const uint32_t *)ctx->prop_data);
        }
        if (ctx->prop_name[0]=='#'&&ctx->prop_name[1]=='s'&&
            ctx->prop_name[2]=='i'&&ctx->prop_name[3]=='z'&&
            ctx->prop_name[4]=='e'&&ctx->prop_name[5]=='-'&&
            ctx->prop_name[6]=='c'&&ctx->prop_name[7]=='e'&&
            ctx->prop_name[8]=='l'&&ctx->prop_name[9]=='l'&&
            ctx->prop_name[10]=='s'&&ctx->prop_name[11]=='\0' &&
            ctx->prop_len >= 4) {
            nc->size_cells = (int)fdt32_to_cpu(
                (const uint32_t *)ctx->prop_data);
        }
        return FDT_WALK_CONTINUE;
    }

    /* Root node: check own cells */
    if (!nc->known_cells && ctx->depth == 0 && nc->num_components == 0) {
        if (ctx->prop_name[0]=='#'&&ctx->prop_name[1]=='a'&&
            ctx->prop_name[2]=='d'&&ctx->prop_name[3]=='d'&&
            ctx->prop_name[4]=='r'&&ctx->prop_name[5]=='e'&&
            ctx->prop_name[6]=='s'&&ctx->prop_name[7]=='s'&&
            ctx->prop_name[8]=='-'&&ctx->prop_name[9]=='c'&&
            ctx->prop_name[10]=='e'&&ctx->prop_name[11]=='l'&&
            ctx->prop_name[12]=='l'&&ctx->prop_name[13]=='s'&&
            ctx->prop_name[14]=='\0' && ctx->prop_len >= 4)
            nc->addr_cells = (int)fdt32_to_cpu(
                (const uint32_t *)ctx->prop_data);
        if (ctx->prop_name[0]=='#'&&ctx->prop_name[1]=='s'&&
            ctx->prop_name[2]=='i'&&ctx->prop_name[3]=='z'&&
            ctx->prop_name[4]=='e'&&ctx->prop_name[5]=='-'&&
            ctx->prop_name[6]=='c'&&ctx->prop_name[7]=='e'&&
            ctx->prop_name[8]=='l'&&ctx->prop_name[9]=='l'&&
            ctx->prop_name[10]=='s'&&ctx->prop_name[11]=='\0' &&
            ctx->prop_len >= 4)
            nc->size_cells = (int)fdt32_to_cpu(
                (const uint32_t *)ctx->prop_data);
    }

    /* Inside target: parse reg */
    if (nc->in_target) {
        if (ctx->prop_name[0]=='r'&&ctx->prop_name[1]=='e'&&
            ctx->prop_name[2]=='g'&&ctx->prop_name[3]=='\0') {
            int tc = nc->addr_cells + nc->size_cells;
            if (tc > 0 && ctx->prop_len >= (uint32_t)(tc * 4)) {
                const uint32_t *d = (const uint32_t *)ctx->prop_data;
                nc->reg_addr = read_cells(d, nc->addr_cells);
                nc->reg_size = read_cells(d + nc->addr_cells, nc->size_cells);
                nc->found = 1;
                return FDT_WALK_STOP;
            }
        }
    }

    return FDT_WALK_CONTINUE;
}

UNPAGED int
fdt_get_node_reg(const void *fdt, const char *path,
                 int addr_cells, int size_cells,
                 uint64_t *reg_addr, uint64_t *reg_size)
{
    struct node_path_ctx nc;
    if (!fdt || !path || !reg_addr || !reg_size) return -1;

    nc.path = path;
    nc.num_components = fdt_path_num_components(path);

    if (addr_cells >= 1 && size_cells >= 1) {
        nc.addr_cells = addr_cells;
        nc.size_cells = size_cells;
        nc.known_cells = 1;
    } else {
        nc.addr_cells = 2;
        nc.size_cells = 2;
        nc.known_cells = 0;
    }

    nc.target_depth = nc.num_components;
    nc.in_target = 0;
    nc.reg_addr = 0; nc.reg_size = 0; nc.found = 0;

    fdt_walk(fdt, np_on_node_begin, np_on_node_end, np_on_prop, &nc);

    if (nc.found) { *reg_addr = nc.reg_addr; *reg_size = nc.reg_size; return 1; }
    return 0;
}

/* =========================================================================
 * UART info parsing — full stdout-path lookup
 *
 * Locates the boot console UART by:
 *   1. Reading stdout-path from /chosen
 *   2. Resolving alias via /aliases
 *   3. Walking to the UART node and parsing reg
 *   4. Falling back to QEMU virt PL011 at 0x09000000
 * ========================================================================= */

UNPAGED int
fdt_get_uart_info(const void *fdt, uint64_t *uart_addr)
{
    if (!fdt || !uart_addr) return -1;

    *uart_addr = 0x09000000ULL;  /* Default fallback */

    const char *sp = fdt_get_chosen_stdout(fdt);
    if (!sp || sp[0] == '\0') return 0;

    char buf[64];
    fdt_strip_stdout_options(sp, buf, sizeof(buf));
    if (buf[0] == '\0') return 0;

    char resolved[64];
    const char *node_path;

    if (buf[0] != '/') {
        /* Alias — resolve via /aliases */
        int ret = fdt_resolve_alias(fdt, buf, resolved, sizeof(resolved));
        if (ret < 0) {
            /* Fallback: treat as direct node name under root */
            resolved[0] = '/';
            int i;
            for (i = 0; buf[i] != '\0' && i < (int)sizeof(resolved) - 2; i++)
                resolved[i + 1] = buf[i];
            resolved[i + 1] = '\0';
            node_path = resolved;
        } else {
            node_path = resolved;
        }
    } else {
        node_path = buf;
    }

    uint64_t ra, rs;
    if (fdt_get_node_reg(fdt, node_path, -1, -1, &ra, &rs) == 1 && rs > 0) {
        *uart_addr = ra;
        return 1;
    }

    *uart_addr = 0x09000000ULL;
    return 0;
}

/* =========================================================================
 * Debug: DTB summary dump
 * ========================================================================= */

#if defined(FDT_VERBOSE) && FDT_VERBOSE

UNPAGED static void
fdt_put_hex(void (*putc)(char), uint64_t val, int digits)
{
    const char *h = "0123456789ABCDEF";
    int i;
    for (i = (digits * 4) - 4; i >= 0; i -= 4)
        putc(h[(val >> i) & 0xF]);
}

UNPAGED static void
fdt_put_str(void (*putc)(char), const char *s)
{
    if (!s) return;
    while (*s) putc(*s++);
}

UNPAGED void
fdt_dump(const void *fdt, void (*putc)(char))
{
    uint64_t ma, ms;
    int cc;
    const char *ba, *sp;

    if (!fdt || !putc) return;
    if (fdt_validate(fdt, 0) != 0) {
        fdt_put_str(putc, "[FDT] INVALID DTB\r\n");
        return;
    }

    uint32_t total = fdt_total_size(fdt);
    uint32_t ver = fdt32_to_cpu(&fdt_header(fdt)->version);
    uint32_t cver = fdt32_to_cpu(&fdt_header(fdt)->last_comp_version);

    fdt_put_str(putc, "[FDT] DTB detected\r\n");
    fdt_put_str(putc, "[FDT]   Size:       ");
    fdt_put_hex(putc, total, 8);
    fdt_put_str(putc, " bytes\r\n");
    fdt_put_str(putc, "[FDT]   Version:    ");
    fdt_put_hex(putc, ver, 2);
    fdt_put_str(putc, " (compat: ");
    fdt_put_hex(putc, cver, 2);
    fdt_put_str(putc, ")\r\n");

    if (fdt_get_memory(fdt, &ma, &ms) == 1) {
        fdt_put_str(putc, "[FDT]   Memory:     0x");
        fdt_put_hex(putc, ma, 16);
        fdt_put_str(putc, " - 0x");
        fdt_put_hex(putc, ma + ms, 16);
        fdt_put_str(putc, " (");
        fdt_put_hex(putc, ms / (1024 * 1024), 4);
        fdt_put_str(putc, " MB)\r\n");
    }

    cc = fdt_get_cpu_count(fdt);
    fdt_put_str(putc, "[FDT]   CPUs:       ");
    fdt_put_hex(putc, cc, 2);
    fdt_put_str(putc, "\r\n");

    ba = fdt_get_chosen_bootargs(fdt);
    if (ba) {
        fdt_put_str(putc, "[FDT]   Bootargs:   ");
        fdt_put_str(putc, ba);
        fdt_put_str(putc, "\r\n");
    }

    sp = fdt_get_chosen_stdout(fdt);
    if (sp) {
        fdt_put_str(putc, "[FDT]   Stdout:     ");
        fdt_put_str(putc, sp);
        fdt_put_str(putc, "\r\n");
    }
}

#endif /* FDT_VERBOSE */
