//! Rust port of the NetBSD `mkesdb` utility.
//!
//! Usage:
//!   mkesdb [-o output] [-c] [input ...]
//!
//! Generates Escape Sequence Database (ESDB) files for terminal handling.
//! Processes terminal capability descriptions.

use std::collections::BTreeMap;
use std::fs;
use std::io::{BufRead, BufReader, Write};

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let mut argv = &args[1..];
    let mut output: Option<String> = None;
    let mut compact = false;

    while !argv.is_empty() && argv[0].starts_with('-') && argv[0] != "--" {
        let opt = argv[0].clone();
        if opt == "--" { argv = &argv[1..]; break; }
        match opt.as_str() {
            "-o" => {
                argv = &argv[1..];
                if argv.is_empty() { eprintln!("usage: mkesdb [-o output] [-c] [input]"); std::process::exit(1); }
                output = Some(argv[0].clone());
            }
            "-c" => compact = true,
            _ => { eprintln!("usage: mkesdb [-o output] [-c] [input]"); std::process::exit(1); }
        }
        argv = &argv[1..];
    }

    let inputs: Vec<&str> = if argv.is_empty() { vec!["-"] } else { argv.iter().map(|s| s.as_str()).collect() };
    let mut entries: BTreeMap<String, String> = BTreeMap::new();
    let mut section = String::new();

    for fname in &inputs {
        let reader: Box<dyn BufRead> = if *fname == "-" {
            Box::new(BufReader::new(std::io::stdin().lock()))
        } else {
            match fs::File::open(fname) {
                Ok(f) => Box::new(BufReader::new(f)),
                Err(e) => { eprintln!("mkesdb: {fname}: {e}"); std::process::exit(1); }
            }
        };

        for line in reader.lines() {
            let line = match line { Ok(l) => l, Err(_) => break };
            let trimmed = line.trim();

            if trimmed.is_empty() || trimmed.starts_with('#') { continue; }

            if trimmed.starts_with('[') && trimmed.ends_with(']') {
                section = trimmed[1..trimmed.len()-1].to_string();
                continue;
            }

            // Format: key = value
            if let Some(eq) = trimmed.find('=') {
                let key = if section.is_empty() {
                    trimmed[..eq].trim().to_string()
                } else {
                    format!("{}.{}", section, trimmed[..eq].trim())
                };
                let value = trimmed[eq+1..].trim().to_string();
                if !key.is_empty() {
                    entries.insert(key, value);
                }
            }
        }
    }

    let out_name = output.unwrap_or_else(|| "esdb.c".to_string());
    let mut out = fs::File::create(&out_name)
        .unwrap_or_else(|_| { eprintln!("mkesdb: cannot create {out_name}"); std::process::exit(1); });

    writeln!(out, "/* Generated by mkesdb */").ok();
    writeln!(out, "#include <esdb.h>\n").ok();
    writeln!(out, "static const struct esdb_entry esdb_table[{}] = {{", entries.len()).ok();
    for (key, value) in &entries {
        if compact {
            let escaped = escape_string(value);
            writeln!(out, "    {{ \"{}\", \"{}\" }},", key, escaped).ok();
        } else {
            writeln!(out, "    {{ {:3},  \"{}\" }},", entries.len(), value).ok();
        }
    }
    writeln!(out, "}};").ok();
    writeln!(out, "const int esdb_nentries = {};", entries.len()).ok();
}

fn escape_string(s: &str) -> String {
    let mut result = String::new();
    for c in s.chars() {
        match c {
            '\\' => result.push_str("\\\\"),
            '"' => result.push_str("\\\""),
            '\n' => result.push_str("\\n"),
            '\r' => result.push_str("\\r"),
            '\t' => result.push_str("\\t"),
            _ if c.is_control() => {
                result.push_str(&format!("\\x{:02x}", c as u8));
            }
            _ => result.push(c),
        }
    }
    result
}
